version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # or any runtime just to satisfy the requirement
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  build:
    commands:
      - echo "Destroying infrastructure..."
      - terraform init
      - terraform destroy -auto-approve -lock=false
